ENEMY_SOUL_CODES = {
    ["administrator"] = "enemy_soul_administrator",
    ["phrend"] = "enemy_soul_phrend",
    ["beefboy"] = "enemy_soul_beefboy",
    ["blobs"] = "enemy_soul_blobs",
    ["fleemers"] = "enemy_soul_fleemers",
    ["crabs"] = "enemy_soul_crabs",
    ["chompignom"] = "enemy_soul_chompignom",
    ["husher"] = "enemy_soul_husher",
    ["autobolt"] = "enemy_soul_autobolt",
    ["zombie_foxes"] = "enemy_soul_zombie_foxes",
    ["frogs"] = "enemy_soul_frogs",
    ["lost_echo"] = "enemy_soul_lost_echo",
    ["gunslinger"] = "enemy_soul_gunslinger",
    ["hedgehogs"] = "enemy_soul_hedgehogs",
    ["laser_trap"] = "enemy_soul_laser_trap",
    ["envoy"] = "enemy_soul_envoy",
    ["garden_knight"] = "enemy_soul_garden_knight",
    ["librarian"] = "enemy_soul_librarian",
    ["plover"] = "enemy_soul_plover",
    ["fairies"] = "enemy_soul_fairies",
    ["scavengers"] = "enemy_soul_scavengers",
    ["boss_scavenger"] = "enemy_soul_boss_scavenger",
    ["tentacle"] = "enemy_soul_tentacle",
    ["rudelings"] = "enemy_soul_rudelings",
    ["spiders"] = "enemy_soul_spiders",
    ["siege_engine"] = "enemy_soul_siege_engine",
    ["slorm"] = "enemy_soul_slorm",
    ["baby_slorm"] = "enemy_soul_baby_slorm",
    ["voidling"] = "enemy_soul_voidling",
    ["custodians"] = "enemy_soul_custodians",
    ["voidtouched"] = "enemy_soul_voidtouched",
    ["the_heir"] = "enemy_soul_the_heir",
}

ENEMY_ACCESS_RULES = {
    ["administrator"] = {soul = "administrator", rule = "sword"},
    ["administrator_coffee"] = {soul = "administrator", rule = "soul_only"},
    ["autobolt"] = {soul = "autobolt", rule = "sword_or_gun"},
    ["autobolt_gap"] = {soul = "autobolt", rule = "autobolt_gap"},
    ["baby_slorm"] = {soul = "baby_slorm", rule = "melee_or_wand_or_gun"},
    ["beefboy"] = {soul = "beefboy", rule = "beefboy"},
    ["blob"] = {soul = "blobs", rule = "melee"},
    ["blob_ice_grapple"] = {soul = "blobs", rule = "ice_grapple_blob"},
    ["boss_scavenger"] = {soul = "boss_scavenger", rule = "boss_scavenger"},
    ["chompignom"] = {soul = "chompignom", rule = "sword"},
    ["crabbit"] = {soul = "crabs", rule = "melee"},
    ["crabbit_shell"] = {soul = "crabs", rule = "crab_shell"},
    ["crabbo"] = {soul = "crabs", rule = "melee"},
    ["custodian"] = {soul = "custodians", rule = "sword_or_gun"},
    ["custodian_candelabra"] = {soul = "custodians", rule = "sword_or_gun"},
    ["custodian_sword"] = {soul = "custodians", rule = "sword_or_gun"},
    ["envoy"] = {soul = "envoy", rule = "envoy"},
    ["envoy_bridge"] = {soul = "envoy", rule = "envoy_combat"},
    ["envoy_combat"] = {soul = "envoy", rule = "envoy_combat"},
    ["envoy_shop"] = {soul = "envoy", rule = "envoy_shop"},
    ["fairy"] = {soul = "fairies", rule = "fairy"},
    ["fairy_gauntlet"] = {soul = "fairies", rule = "fairy_gauntlet"},
    ["fleemer"] = {soul = "fleemers", rule = "melee"},
    ["fleemer_big"] = {soul = "fleemers", rule = "sword"},
    ["fleemer_fencer"] = {soul = "fleemers", rule = "sword"},
    ["fleemer_gauntlet"] = {soul = "fleemers", rule = "sword"},
    ["fox_enemy"] = {soul = "zombie_foxes", rule = "sword"},
    ["fox_enemy_zombie"] = {soul = "zombie_foxes", rule = "sword"},
    ["frog"] = {soul = "frogs", rule = "sword"},
    ["frog_atoll"] = {soul = "frogs", rule = "frog_atoll"},
    ["frog_secret"] = {soul = "frogs", rule = "frog_secret"},
    ["frog_small"] = {soul = "frogs", rule = "sword"},
    ["frog_spear"] = {soul = "frogs", rule = "sword"},
    ["frog_stairs_lower"] = {soul = "frogs", rule = "frog_stairs_lower"},
    ["garden_knight"] = {soul = "garden_knight", rule = "sword"},
    ["guard_captain"] = {soul = "rudelings", rule = "sword"},
    ["gunslinger"] = {soul = "gunslinger", rule = "sword"},
    ["hedgehog"] = {soul = "hedgehogs", rule = "melee"},
    ["husher"] = {soul = "husher", rule = "sword_orb"},
    ["laser_cathedral_orb"] = {soul = "laser_trap", rule = "laser_cathedral_orb"},
    ["laser_cathedral_shop"] = {soul = "laser_trap", rule = "laser_cathedral_shop"},
    ["laser_trap"] = {soul = "laser_trap", rule = "melee"},
    ["librarian"] = {soul = "librarian", rule = "librarian"},
    ["lost_echo"] = {soul = "lost_echo", rule = "sword"},
    ["phrend"] = {soul = "phrend", rule = "melee"},
    ["plover"] = {soul = "plover", rule = "melee"},
    ["rudeling"] = {soul = "rudelings", rule = "sword"},
    ["rudeling_patrol"] = {soul = "rudelings", rule = "sword"},
    ["rudeling_shield"] = {soul = "rudelings", rule = "sword"},
    ["scavenger"] = {soul = "scavengers", rule = "sword_or_wand"},
    ["scavenger_miner"] = {soul = "scavengers", rule = "sword_or_wand"},
    ["scavenger_sniper"] = {soul = "scavengers", rule = "scavenger_sniper"},
    ["scavenger_support"] = {soul = "scavengers", rule = "sword_or_wand"},
    ["siege_engine"] = {soul = "siege_engine", rule = "siege_engine"},
    ["slorm"] = {soul = "slorm", rule = "sword_or_wand_or_gun"},
    ["spider"] = {soul = "spiders", rule = "sword"},
    ["tentacle"] = {soul = "tentacle", rule = "sword"},
    ["voidling"] = {soul = "voidling", rule = "sword_or_gun"},
    ["voidtouched"] = {soul = "voidtouched", rule = "voidtouched"},
}
